# Generated by Django 6.0.4 on 2026-04-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_type_alter_product_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category',
        ),
    ]
